name: Notion Daily Generator
on:
  schedule:
    - cron: "8 15 * * *" # 毎日 0 時 8 分(JST)に実行
  workflow_dispatch:

jobs:
  notion-daily-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: python notion_daily_generator.py
